name: Deploy Demo Version Index

on:
  workflow_dispatch:
    # Allows for manual triggering.
  workflow_call:
    # Allows calling this from another workflow with "uses:".
    # The release workflow will trigger this as a final step after updating the
    # appspot deployment.
    secrets:
      APPENGINE_DEPLOY_KEY:
        required: true
  push:
    branches:
      - main
    paths:
      - .github/workflows/demo-version-index.yaml
      - app-engine/demo-version-index/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  appspot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # We need a list of all tags for this, so fetch the entire history.
          fetch-depth: 0
          persist-credentials: false

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.APPENGINE_DEPLOY_KEY }}'

      - name: Generate static content
        run: python3 app-engine/demo-version-index/generate.py

      - uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: shaka-player-demo
          version: index
          working_directory: app-engine/demo-version-index/
          promote: false

